config/routes.rb
Subjects::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'subjects#index'

  resources :subjects, :only => [:new, :index, :create, :show] do
    resources :reviews, :only => [:new, :show, :create]
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

	include Rakismet::Model

	belongs_to :subject
  belongs_to :user

  attr_accessible :difficulty, :workload, :review, :recommend, :overall, :approved
  
  

  validates :difficulty, :workload, :overall, :presence => true
  validates_inclusion_of :recommend, :in => [true, false]
  validates :review, :length => { :minimum =>20 }, :allow_blank => true

  rakismet_attrs  :author => proc { user.name },
                  :author_email => proc { user.email }, 
                  :author_url => 'http://high-moon-5823.herokuapp.com/',
                  :content => :review

  scope :is_approved, :conditions => { :approved => true }
	scope :has_text_review, where( "review <> ''" )
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  require 'facets/float'
  attr_accessible :code, :title
  has_many :reviews

  validates :code, :title, :presence => true

  validates :code, :length => { :minimum => 5, :maximum => 7 }

  validates :code, :uniqueness => true
  validates :title, :uniqueness => true


  def average_difficulty
  	if self.reviews.is_approved.count > 0
  		self.reviews.is_approved.average(:difficulty).round(2)
  	else
  		0.0
  	end
  end

  def average_overall
    if self.reviews.count > 0
      self.reviews.average(:overall).round(2)
    else
      0.0
    end
  end

  def average_workload
  	if self.reviews.count > 0
  		self.reviews.average(:workload).round(2)
  	else
  		0.0
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :course, :name
  # attr_accessible :title, :body

  validates :name, :length => { :minimum => 5 }
  validates :course, :length => { :minimum => 5 }
  
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]

  # GET subjects/1/reviews/1
  # GET subjects/1/reviews/1.json
  def show
    @subject = Subject.find(params[:subject_id])
    @review = @subject.reviews.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @review }
    end
  end

  # GET subjects/1/reviews/new
  # GET subjects/1/reviews/new.json
  def new
    @subject = Subject.find(params[:subject_id])
    @review = @subject.reviews.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @review }
    end
  end

  # POST subjects/1/reviews
  # POST subjects/1/reviews.json
  def create
    @subject = Subject.find(params[:subject_id])
    @review = @subject.reviews.build(params[:review])
    @review.user = current_user
    if @review.review.empty?
      @review.approved = true
    else
      if @review.spam? 
        logger.info "SPAM"
        @review.approved = false
      else
        logger.info "NOT SPAM"
        @review.approved = true
      end
    end
     
    respond_to do |format|
      if @review.save
        if @review.approved?
          flash[:notice] = "Thanks for the comment."
        else
          flash[:error] = "Unfortunately this comment is considered spam by Akismet. " + 
                      "It will show up once it has been approved by the administrator."
        end
        format.html { redirect_to(subject_path(@review.subject)) }
        format.json { render :json => @review, :status => :created, :location => [@review.subject, @review] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @review.errors, :status => :unprocessable_entity }
      end
    end

  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def score_color(score)
  	if score > 7.5
  	  "progress-danger"
  	elsif score < 5.0
	  "progress-success"
  	else
  	  "progress-info"
  	end
  end

  def recommend_format(recommend_value)
  	recommend_value ""
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BetterLEX</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "BetterLEX", subjects_path, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><%= link_to "Home", subjects_path %></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to('Edit Profile', edit_user_registration_path) %>    
              </li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
              </li>
            <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>  
              </li>
            <% end %>
            <% if not user_signed_in? %>
              <li>
                <%= link_to('Sign up', new_user_registration_path)  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
    <hr>
  </div>
</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@review.subject, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :overall, :collection => 1..10, :selected => 5 %>
  <%= f.input :workload, :collection => 1..10, :selected => 5 %>
  <%= f.input :difficulty, :collection => 1..10, :selected => 5 %>
  <%= f.input :recommend,     :as => :radio_buttons %> 
    <div class="control-group">
            
            <div class="controls docs-input-sizes">
             
              <div class="alert alert-info" style="width: 460px">
                You can optionally add a review. Try and be descriptive.
              </div>
            </div>
          </div>
  <%= f.input :review, :input_html => { :rows => 10, :style => "width: 500px;"}, :label => "A brief description of your experiences" %>
  
  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>

<% end %>

app/views/reviews/new.html.erb
<div class="page-header">
  
   <%= link_to subject_path(@review.subject), :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>Add review for <%= @review.subject.title %> </h1>
</div>
<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Difficulty:</b>
  <%= @review.difficulty %>
</p>

<p>
  <b>Workload:</b>
  <%= @review.workload %>
</p>

<p>
  <b>Review:</b>
  <%= @review.review %>
</p>

<%= link_to 'Back', subject_path(@review.subject) %>

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/subjects/index.html.erb
<div class="page-header">
  <%= link_to new_subject_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Subject
  <% end %>
  <h1>Listing subjects</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Reviews</th>
      <th>Average Difficulty</th>
      <th>Average Workload</th>
    </tr>
  </thead>

  <tbody>
<% @subjects.each do |subject| %>
    <tr>
      <td><%= link_to subject.code, subject_path(subject) %></td>
      <td><%= link_to subject.title, subject_path(subject) %></td>
      <td><%= subject.reviews.is_approved.has_text_review.count %></td>
      <td><%= subject.average_difficulty %></td>
      <td><%= subject.average_workload %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/subjects/new.html.erb
<div class="page-header">
  <%= link_to subjects_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New subject</h1>
</div>

<%= render 'form' %>

app/views/subjects/show.html.erb
<div class="page-header">
  <%= link_to subjects_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to new_subject_review_path(@subject), :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    Review this subject
  <% end %>
  <h1>
    <%= @subject.code %>
    -
    <%= @subject.title %>
  </h1>

</div>
<div style="width: 50%;">
  <h3>Overall rating is <%= @subject.average_overall %></h3>
  <div class="progress <%= score_color(@subject.average_overall) %>">
    <div class="bar" style="width: <%= number_to_percentage(@subject.average_overall * 10) %>;"></div>
  </div>
  <h3>Average difficulty is <%= @subject.average_difficulty %></h3>
  <div class="progress <%= score_color(@subject.average_difficulty) %>">
    <div class="bar" style="width: <%= number_to_percentage(@subject.average_difficulty * 10) %>;"></div>
  </div>
  <h3>Average workload is <%= @subject.average_workload %></h3>
  <div class="progress <%= score_color(@subject.average_workload) %>">
    <div class="bar" style="width: <%= number_to_percentage(@subject.average_workload * 10) %>;"></div>
  </div>
</div>
<hr>
<h2><%= pluralize(@subject.reviews.is_approved.has_text_review.count, "review") %></h2>
<hr>
<% @subject.reviews.is_approved.has_text_review.each do |review| %>
  <h3>
    <%= review.user.name %> 
  </h3> 
  <dl class="dl-horizontal">
    <dt>Overall</dt>
    <dd><%= review.overall %></dd>
    <dt>Difficulty</dt>
    <dd><%= review.difficulty %></dd>
    <dt>Workload</dt>
    <dd><%= review.workload %></dd>
    <dt>Recommended</dt>
    <dd><%= review.recommend ? "Yes" : "No" %></dd>
  </dl>
  <blockquote>
    <%= review.review %>
  </blockquote>
<% end %>